---
abstract: 'Insert argument validator code in output code'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Module::Build: 0.3601
  Test::More: 0.88
  blib: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Rinci-Validate
requires:
  Data::Sah: 0.10
  Dist::Zilla: 0
  Log::Any: 0
  Perinci::Access::Perl: 0.38
resources:
  homepage: http://metacpan.org/release/Dist-Zilla-Plugin-Rinci-Validate
  repository: http://github.com/sharyanto/perl-Dist-Zilla-Plugin-Rinci-Validate
version: 0.07
